// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHDHTacJisU2ZDOOWsBETINXYDtyKjHE4',
    appId: '1:842086777711:web:76cfb5ac144f98b3ea9e9a',
    messagingSenderId: '842086777711',
    projectId: 'uceva-taller3-universidades',
    authDomain: 'uceva-taller3-universidades.firebaseapp.com',
    storageBucket: 'uceva-taller3-universidades.firebasestorage.app',
    measurementId: 'G-4KXWYHHLTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1NGDMO9goWw4E-S11Y70-Gm0sXDxpg0o',
    appId: '1:842086777711:android:5216b027411e6a70ea9e9a',
    messagingSenderId: '842086777711',
    projectId: 'uceva-taller3-universidades',
    storageBucket: 'uceva-taller3-universidades.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuT2Su1oOsiaTOXO4zRCGNZxdsKCDlvWQ',
    appId: '1:842086777711:ios:667440572f6b108cea9e9a',
    messagingSenderId: '842086777711',
    projectId: 'uceva-taller3-universidades',
    storageBucket: 'uceva-taller3-universidades.firebasestorage.app',
    iosBundleId: 'com.example.registroClases',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuT2Su1oOsiaTOXO4zRCGNZxdsKCDlvWQ',
    appId: '1:842086777711:ios:667440572f6b108cea9e9a',
    messagingSenderId: '842086777711',
    projectId: 'uceva-taller3-universidades',
    storageBucket: 'uceva-taller3-universidades.firebasestorage.app',
    iosBundleId: 'com.example.registroClases',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHDHTacJisU2ZDOOWsBETINXYDtyKjHE4',
    appId: '1:842086777711:web:10a01381d7c89741ea9e9a',
    messagingSenderId: '842086777711',
    projectId: 'uceva-taller3-universidades',
    authDomain: 'uceva-taller3-universidades.firebaseapp.com',
    storageBucket: 'uceva-taller3-universidades.firebasestorage.app',
    measurementId: 'G-D00TWYR71R',
  );
}
